### ISSUE TITLE
error_message: 'identity_verification_id must be filled.',

### ISSUE THREAD

**Issue by dfvalenciaviamericas** [plaid/idv-quickstart#18]
I am trying to create a link token for IDV, below you can see the snnipet of code use it, but always i am getting the following message error error_message: 'identity_verification_id must be filled.', even where all fields have been verified previously

app.post('/api/create_link_token', async (req, res, next) => {
  let payload = {};
    payload = {
      user: {
        client_user_id: req.sessionID,
        email_address: 'testUser@hotmail.com',
      },
      client_name: 'Plaid Tiny Quickstart - React Native',
      language: 'en',
      products: ['identity_verification'],
      country_codes: ['US'],
      identity_verification: {
        template_id: ID_VER_TEMPLATE,
      },
    };
 
  const tokenResponse = await client.linkTokenCreate(payload);
  res.json(tokenResponse.data);
});

**Comment by Scimecajane** [comment]
Ok when will the payment be made

**Comment by phoenixy1** [comment]
I copied and pasted your JSON request body into Postman (substituting an actual template ID and client_user_id) and it worked fine. There may be an issue with how you are calling this method or populating some of the fields that use variables rather than with the structure of the request itself. Can you try the following:

1) Manually replacing the variable fields (like the template and the client_user_id) with the correct strings.
2) Try using Postman rather than node and seeing if you can get this to work
3) Run the actual IDV-Quickstart and see if that works for you. If it does, try modifying the code in the Quickstart rather than writing code from scratch.
